services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: supertp
      MYSQL_DATABASE: tp
      MYSQL_USER: cdiiv
      MYSQL_PASSWORD: superprof
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80